-- HomeOfferFlow revenue-led roadmap order.
-- Priority is based on addressable market adoption, ease of shipping/adoption,
-- and proximity to recurring revenue. Product price is intentionally excluded.

with revenue_priority (
  slug,
  priority,
  priority_tier,
  market_adoption_score,
  ease_of_entry_score,
  revenue_proximity_score,
  priority_rationale,
  next_action
) as (
  values
    ('seller-temporary-lease', 1, 'ship_now', 4, 5, 5,
      'Already passed staging, removes a known transaction limitation, and can reach the agent market with minimal remaining work.',
      'Ship the verified production unlock, run the focused production check, and close the release gate.'),
    ('agent-dashboard', 2, 'grow_now', 5, 4, 5,
      'Individual agents are the broadest low-friction customer entry point; a dependable daily workspace improves activation, retention, and repeat packet volume.',
      'Finish saved-offer reliability, resume and duplicate flows, SignWell status, usage visibility, and first-session onboarding.'),
    ('subscription-usage-management', 3, 'grow_now', 5, 4, 5,
      'Every self-serve agent account depends on reliable conversion, renewal, limits, and recovery, making this the shortest path from usage to recurring revenue.',
      'Complete checkout-to-renewal lifecycle QA, failed-payment recovery, cancellation, and usage-limit messaging.'),
    ('seo-hero-update', 4, 'grow_now', 5, 5, 3,
      'The approved plain-English offer-preparation message is fast to ship and reduces acquisition friction across agent and consumer traffic.',
      'Deploy the approved hero, role-specific calls to action, and conversion event tracking.'),
    ('founding-partner-pilot', 5, 'validate_now', 3, 5, 4,
      'A lightweight founding-partner intake can begin monetization conversations before transaction volume supports a full two-sided marketplace.',
      'Publish the application, qualify one partner per priority category and market, and sell only documented pilot placements without promising volume or exclusivity.'),
    ('seller-disclosure-uploads', 6, 'grow_now', 5, 4, 4,
      'Disclosure upload support expands usefulness for the agent-led market without requiring HomeOfferFlow to generate seller disclosures.',
      'Make listing-disclosure upload, ordering, validation, and packet confirmation frictionless.'),
    ('ai-offer-competitiveness', 7, 'validate_next', 4, 3, 4,
      'Agent AI adoption is strong and the feature differentiates the offer workflow, but accuracy and compliance concerns require a controlled release.',
      'Run a benchmark set against expert review, expose confidence and rationale, and launch to a limited agent cohort.'),
    ('team-support', 8, 'expand_next', 4, 3, 4,
      'Team invitations and shared workflows let successful individual-agent adoption spread to multiple seats with less friction than an enterprise sale.',
      'Finish invitations, roles, shared defaults, seat administration, and team-level usage reporting.'),
    ('brokerage-branding', 9, 'expand_next', 4, 4, 4,
      'Branding reduces resistance from teams and brokerages and can reuse the existing packet and email surfaces.',
      'Add secure logo upload plus brokerage colors, contact defaults, disclaimer, packet, and email propagation.'),
    ('seller-workflow', 10, 'expand_next', 5, 2, 4,
      'The agent-assisted seller market is large, but a complete listing-side packet requires materially more form, signature, and QA work.',
      'Define an agent-led seller packet MVP and its first golden scenarios before adding direct-to-seller complexity.'),
    ('broker-dashboard', 11, 'expand_next', 4, 2, 4,
      'Brokerage distribution can create multi-seat revenue, but procurement and workflow change are slower than individual-agent adoption.',
      'Pilot brokerage reporting only after team membership and branding are dependable.'),
    ('automated-visual-regression', 12, 'scale_safely', 4, 3, 4,
      'Faster, safer form releases protect trust and reduce the manual QA bottleneck that limits catalog expansion.',
      'Create approved page and field-region baselines for the golden packet suite.'),
    ('production-deployment-checklist', 13, 'scale_safely', 4, 5, 3,
      'A single release gate is inexpensive and prevents avoidable incidents while the product expands.',
      'Make the Supabase release record the authoritative deploy, QA, monitoring, and rollback gate.'),
    ('additional-texas-forms', 14, 'catalog_expansion', 4, 3, 3,
      'More verified Texas forms expand transaction coverage, but each form should be justified by frequency and shipped independently.',
      'Rank requested forms by observed blocked transactions and unlock one high-frequency form at a time.'),
    ('admin-dashboard', 15, 'operations', 3, 4, 3,
      'Operational visibility supports growth but does not itself create customer adoption.',
      'Publish the authenticated Supabase tracker views and verify the admin-only workflow.'),
    ('supabase-product-tracker', 16, 'operations', 3, 5, 3,
      'The tracker improves prioritization and release discipline, but it is an internal revenue enabler rather than a customer feature.',
      'Publish the prepared dashboard branch and verify the authenticated production view.'),
    ('seller-financing', 17, 'targeted_forms', 3, 2, 3,
      'Seller financing broadens transaction coverage but is less common and more complex than the agent-platform work above it.',
      'Measure blocked demand, then build and visually audit one dedicated seller-financing packet.'),
    ('loan-assumption', 18, 'targeted_forms', 3, 2, 3,
      'Loan assumptions are valuable in a subset of transactions but require dedicated form and financing QA.',
      'Measure blocked demand, then build and visually audit one dedicated assumption packet.'),
    ('paragraph4-residential-lease', 19, 'targeted_forms', 3, 2, 3,
      'Residential lease exceptions improve completeness but apply to a narrower set of buyer offers.',
      'Obtain the correct form, map the checkbox and attachment, and run a dedicated signed packet audit.'),
    ('partner-marketplace', 20, 'later_scale', 3, 2, 3,
      'Partner monetization becomes attractive after transaction volume is established; launching it too early creates a two-sided adoption problem.',
      'Defer full marketplace work until agent activation and monthly packet volume reach a stable threshold.'),
    ('fsbo-workflow', 21, 'later_scale', 1, 3, 2,
      'Direct FSBO is a small and shrinking share of completed sales, so it should not outrank the agent-led buyer and seller markets.',
      'Maintain lead capture, but defer full fulfillment until the agent-led seller workflow is proven.'),
    ('paragraph4-fixture-lease', 22, 'targeted_forms', 2, 2, 2,
      'Fixture-lease transactions are narrower than the core agent workflow and need a dedicated form release.',
      'Collect blocked-demand evidence before beginning mapping and QA.'),
    ('paragraph4-natural-resource-lease', 23, 'targeted_forms', 2, 2, 2,
      'Natural-resource lease transactions are geographically and transactionally narrow.',
      'Collect blocked-demand evidence before beginning mapping and QA.'),
    ('hydrostatic-addendum', 24, 'targeted_forms', 2, 2, 2,
      'The addendum expands edge-case coverage but has lower adoption potential than the agent-platform roadmap.',
      'Collect request frequency and obtain the current official form before implementation.'),
    ('environmental-assessment-addendum', 25, 'targeted_forms', 2, 2, 2,
      'The addendum serves a narrower transaction segment and should follow observed demand.',
      'Collect request frequency and obtain the current official form before implementation.'),
    ('mineral-reservation-addendum', 26, 'targeted_forms', 2, 2, 2,
      'The addendum serves a narrower transaction segment and should follow observed demand.',
      'Collect request frequency and obtain the current official form before implementation.'),
    ('state-expansion', 27, 'deferred', 5, 1, 2,
      'The national market is large, but entering another state before Texas workflows stabilize creates high form, legal, QA, and support friction.',
      'Resume only after Texas agent activation, retention, and seller-side adoption are proven.'),
    ('trec-20-19-buyer-offer', 28, 'maintenance', 5, 5, 5,
      'This is the live core product and no longer competes as unfinished roadmap work.',
      'Maintain locked coordinates and monitor production regressions.'),
    ('buyer-temporary-lease', 29, 'maintenance', 3, 5, 5,
      'This path is already in production and moves to regression maintenance.',
      'Regression-test after packet-assembly changes.'),
    ('signwell-status-tracking', 30, 'maintenance', 5, 5, 5,
      'The production foundation is complete and moves to reliability monitoring.',
      'Monitor webhooks, refresh behavior, and delivery failures.')
)
update public.hof_roadmap_items as item
set
  priority = ranked.priority,
  next_action = ranked.next_action,
  metadata = coalesce(item.metadata, '{}'::jsonb) || jsonb_build_object(
    'priority_model', 'market_adoption_ease_revenue_v1',
    'priority_model_date', '2026-07-21',
    'priority_tier', ranked.priority_tier,
    'market_adoption_score', ranked.market_adoption_score,
    'ease_of_entry_score', ranked.ease_of_entry_score,
    'revenue_proximity_score', ranked.revenue_proximity_score,
    'priority_rationale', ranked.priority_rationale,
    'pricing_weight', 0
  ),
  updated_at = now()
from revenue_priority as ranked
where item.slug = ranked.slug;
