const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const assert=require('node:assert/strict'),{test}=require('node:test');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
function section(start,end){const a=html.indexOf(start),b=html.indexOf(end,a);assert.ok(a>=0&&b>a,start);return html.slice(a,b);}
const valid={financing:'seller_financing',price:'500000.55',sellerFinancingCreditDays:'7',sellerFinancingCreditDocuments:['credit_report'],sellerFinancingCreditOther:'',
  sellerFinancingNoteAmount:'250000.50',sellerFinancingInterestRate:'6.25',sellerFinancingPaymentPlan:'monthly_installments',sellerFinancingOnePaymentDueAfterMonths:'',sellerFinancingOnePaymentInterestTiming:'',
  sellerFinancingInstallmentAmount:'1800.25',sellerFinancingInstallmentInterestStyle:'including_interest',sellerFinancingInstallmentBeginsAfterMonths:'1',sellerFinancingPayoffAfterMonths:'180',sellerFinancingInterestOnlyMonths:'',
  sellerFinancingPropertyTransfer:'consent_required',sellerFinancingCasualtyInsurance:'required',sellerFinancingEscrow:'required',sellerFinancingThirdPartyServicer:'will',sellerFinancingEscrowCostPaidBy:'buyer',
  buyer1:'QA Buyer',buyerEmail:'buyer@example.test',seller1Name:'QA Seller',seller1Email:'seller@example.test',leases:'no'};
function setup(){
  const fields=new Map(),radio={financing:'seller_financing',leases:'no'},docs=['credit_report','employment','funds','financial_statement','other'].map(value=>({value,checked:false}));
  const el=id=>{if(!fields.has(id))fields.set(id,{value:'',checked:false,style:{},dataset:{},textContent:'',innerHTML:'',setAttribute(){},removeAttribute(){},insertAdjacentHTML(_p,value){this.innerHTML+=value;}});return fields.get(id);};
  const c=vm.createContext({state:{data:{...valid}},window:{},document:{getElementById:el,querySelectorAll:s=>s.includes('sellerFinancingCreditDocuments')?docs.filter(x=>!s.endsWith(':checked')||x.checked):[],querySelector:s=>s.includes('name="financing"')?{value:radio.financing}:null},
    getVal:id=>String(el(id).value??'').trim(),getRadio:id=>radio[id]||'',setPaymentStatus:message=>c.message=message,purchaseSellerSignerIssues:()=>[],hydrostaticInterviewData:()=>({...c.state.data,financing:radio.financing,leases:radio.leases}),escapeAttr:v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])),hasLeadDisclosureUpload:()=>false});
  vm.runInContext(section('  function assumptionAnswerKeys()', '  function environmentalInterviewData()'),c);
  c.restoreSellerFinancingAnswers(valid);el('offerPrice').value=valid.price;docs[0].checked=true;return {c,el,radio,docs};
}
test('valid seller-financing answers match the packet contract',()=>{const {c}=setup();assert.equal(c.sellerFinancingInterviewIssues(c.sellerFinancingInterviewData(),false).length,0);assert.equal(c.validateSellerFinancingInputs(valid),true);});
test('conditional source choices are required and inactive answers are cleared',()=>{const {c}=setup();
  for(const [key,value] of [['sellerFinancingCreditDays','0'],['sellerFinancingCreditDocuments',[]],['sellerFinancingNoteAmount','600000'],['sellerFinancingInterestRate','101'],['sellerFinancingInstallmentAmount',''],['sellerFinancingPayoffAfterMonths','0'],['sellerFinancingEscrowCostPaidBy','']])assert.ok(c.sellerFinancingInterviewIssues({...valid,[key]:value},false).length,key);
  const cleared=c.sellerFinancingAnswers({...valid,financing:'cash'});assert.equal(cleared.sellerFinancing,'no');assert.equal(cleared.sellerFinancingNoteAmount,'');assert.equal(JSON.stringify(cleared.sellerFinancingCreditDocuments),'[]');
});
test('visibility follows payment and escrow choices',()=>{const {c,el}=setup();c.updateSellerFinancingVisibility();assert.equal(el('sellerFinancingDetails').style.display,'block');assert.equal(el('sellerFinancingInstallmentFields').style.display,'block');assert.equal(el('sellerFinancingOnePaymentFields').style.display,'none');assert.equal(el('sellerFinancingEscrowFields').style.display,'flex');assert.equal(el('paymentCalcCard').style.display,'none');});
test('saved answers restore without preselecting choices',()=>{const {c,el,docs}=setup();c.restoreSellerFinancingAnswers({...valid,sellerFinancingPaymentPlan:'one_payment',sellerFinancingCreditDocuments:['funds']});assert.equal(el('sellerFinancingPaymentPlan').value,'one_payment');assert.deepEqual(docs.filter(x=>x.checked).map(x=>x.value),['funds']);const markup=section('        <div id="sellerFinancingDetails"','        <div id="assumptionDetails"');assert.doesNotMatch(markup,/checked(?:\s|=|\/?>)/);});
test('purchase flow collects, validates, reviews, and releases seller financing',()=>{assert.ok(html.includes("Object.assign(s, sellerFinancingAnswers(sellerFinancing));"));assert.equal((html.match(/if \(!validateSellerFinancingInputs\(state.data\)\) return;/g)||[]).length,2);assert.ok(html.includes("atag('Seller Financing Addendum', s.financing === 'seller_financing')"));assert.ok(!html.includes("if (data.sellerFinancing === 'yes') blocked.push('Seller Financing Addendum')"));assert.ok(html.includes("restoreSellerFinancingAnswers(data);"));});
